baseURL = "https://heyuuuu77.github.io/"
languageCode = "zh-cn"
theme = "stack"
title = "Heyuuuu"
copyright = "Heyuuuu"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

# 分页设置
[pagination]
pagerSize = 5

# 永久链接设置
[permalinks]
post = "/posts/:slug/"
page = "/:slug/"

# 主要配置
[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

# 页脚设置
[params.footer]
since = 2024
customText = ""

# 日期格式
[params.dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04"

# 侧边栏设置
[params.sidebar]
emoji = "👋"
subtitle = "简单记录生活点滴"
avatar.enabled = true
avatar.local = true
avatar.src = "img/avatar.png"

# 文章设置
[params.article]
math = false
toc = true
readingTime = true
license.enabled = true
license.default = "Licensed under CC BY-NC-SA 4.0"

# 评论设置
[params.comments]
enabled = false

# 小部件设置
[params.widgets]
homepage = [
    {type = "search"},
    {type = "archives", params = {limit = 5}},
    {type = "categories", params = {limit = 10}},
    {type = "tag-cloud", params = {limit = 10}}
]
page = [
    {type = "toc"}
]

# OpenGraph设置
[params.opengraph]
twitter.site = ""
twitter.card = "summary_large_image"

# 默认图片设置
[params.defaultImage]
opengraph.enabled = false
opengraph.local = false
opengraph.src = ""

# 颜色方案
[params.colorScheme]
toggle = true
default = "auto"

# 图片处理
[params.imageProcessing]
cover.enabled = true
content.enabled = true

# 菜单设置
[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 40

# 社交链接
[[menu.social]]
identifier = "x"
name = "X"
url = "https://x.com/"
params.icon = "brand-twitter"

# 相关文章设置
[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

# Markup设置
[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [["[", "]"], ["$$", "$$"]]
inline = [["(", ")"]]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

# 压缩设置
[minify]
disableXML = true
minifyOutput = true

# 机器人设置
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true