baseURL = "https://stitchqaq.github.io/"
languageCode = "zh-cn"
theme = "stack"
title = "Heyuuuu"
copyright = "© 2024-2025 Heyuuuu"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

# Front Matter 日期配置（优先使用更新时间排序）
[frontmatter]
date = ["lastmod", "date", "publishDate"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]

# 分页设置
[pagination]
pagerSize = 10

# 永久链接设置
[permalinks]
post = "/posts/:slug/"
page = "/:slug/"

# 主要配置
[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

# 页脚设置
[params.footer]
since = 2024
customText = ""

# 日期格式
[params.dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04"

# 侧边栏设置
[params.sidebar]
emoji = "👋"
subtitle = "简单记录生活点滴，分享技术学习心得"
[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

# 文章设置
[params.article]
math = false
toc = true
readingTime = true
[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

# 评论设置
[params.comments]
enabled = false

# 小部件设置
[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"
[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

# OpenGraph设置
[params.opengraph.twitter]
site = ""
card = "summary_large_image"

# 默认图片设置
[params.defaultImage.opengraph]
enabled = false
local = false
src = ""

# 颜色方案
[params.colorScheme]
toggle = true
default = "auto"

# 图片处理
[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

# 菜单设置
[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 10
[menu.main.params]
icon = "home"

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 30
[menu.main.params]
icon = "categories"

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 40
[menu.main.params]
icon = "tag"

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 50
[menu.main.params]
icon = "archives"

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 60
[menu.main.params]
icon = "search"

# 社交链接
[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/heyuuuu77"
[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
[menu.social.params]
icon = "rss"

# 相关文章设置
[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

# Markup设置
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [["[", "]"], ["$$", "$$"]]
inline = [["(", ")"]]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

# 压缩设置
[minify]
disableXML = true
minifyOutput = true

# 机器人设置
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
