// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/budget.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BudgetService_CheckBudget_FullMethodName   = "/budget.BudgetService/CheckBudget"
	BudgetService_DeductBudget_FullMethodName  = "/budget.BudgetService/DeductBudget"
	BudgetService_GetBudgetInfo_FullMethodName = "/budget.BudgetService/GetBudgetInfo"
	BudgetService_RefundBudget_FullMethodName  = "/budget.BudgetService/RefundBudget"
)

// BudgetServiceClient is the client API for BudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Budget Service - 预算管理服务
type BudgetServiceClient interface {
	// 检查预算
	CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error)
	// 扣减预算
	DeductBudget(ctx context.Context, in *DeductBudgetRequest, opts ...grpc.CallOption) (*DeductBudgetResponse, error)
	// 获取预算信息
	GetBudgetInfo(ctx context.Context, in *GetBudgetInfoRequest, opts ...grpc.CallOption) (*GetBudgetInfoResponse, error)
	// 退还预算（竞价失败时）
	RefundBudget(ctx context.Context, in *RefundBudgetRequest, opts ...grpc.CallOption) (*RefundBudgetResponse, error)
}

type budgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBudgetServiceClient(cc grpc.ClientConnInterface) BudgetServiceClient {
	return &budgetServiceClient{cc}
}

func (c *budgetServiceClient) CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_CheckBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) DeductBudget(ctx context.Context, in *DeductBudgetRequest, opts ...grpc.CallOption) (*DeductBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_DeductBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) GetBudgetInfo(ctx context.Context, in *GetBudgetInfoRequest, opts ...grpc.CallOption) (*GetBudgetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetInfoResponse)
	err := c.cc.Invoke(ctx, BudgetService_GetBudgetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) RefundBudget(ctx context.Context, in *RefundBudgetRequest, opts ...grpc.CallOption) (*RefundBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundBudgetResponse)
	err := c.cc.Invoke(ctx, BudgetService_RefundBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetServiceServer is the server API for BudgetService service.
// All implementations must embed UnimplementedBudgetServiceServer
// for forward compatibility.
//
// Budget Service - 预算管理服务
type BudgetServiceServer interface {
	// 检查预算
	CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error)
	// 扣减预算
	DeductBudget(context.Context, *DeductBudgetRequest) (*DeductBudgetResponse, error)
	// 获取预算信息
	GetBudgetInfo(context.Context, *GetBudgetInfoRequest) (*GetBudgetInfoResponse, error)
	// 退还预算（竞价失败时）
	RefundBudget(context.Context, *RefundBudgetRequest) (*RefundBudgetResponse, error)
	mustEmbedUnimplementedBudgetServiceServer()
}

// UnimplementedBudgetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBudgetServiceServer struct{}

func (UnimplementedBudgetServiceServer) CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBudget not implemented")
}
func (UnimplementedBudgetServiceServer) DeductBudget(context.Context, *DeductBudgetRequest) (*DeductBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductBudget not implemented")
}
func (UnimplementedBudgetServiceServer) GetBudgetInfo(context.Context, *GetBudgetInfoRequest) (*GetBudgetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBudgetInfo not implemented")
}
func (UnimplementedBudgetServiceServer) RefundBudget(context.Context, *RefundBudgetRequest) (*RefundBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundBudget not implemented")
}
func (UnimplementedBudgetServiceServer) mustEmbedUnimplementedBudgetServiceServer() {}
func (UnimplementedBudgetServiceServer) testEmbeddedByValue()                       {}

// UnsafeBudgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BudgetServiceServer will
// result in compilation errors.
type UnsafeBudgetServiceServer interface {
	mustEmbedUnimplementedBudgetServiceServer()
}

func RegisterBudgetServiceServer(s grpc.ServiceRegistrar, srv BudgetServiceServer) {
	// If the following call pancis, it indicates UnimplementedBudgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BudgetService_ServiceDesc, srv)
}

func _BudgetService_CheckBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).CheckBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_CheckBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).CheckBudget(ctx, req.(*CheckBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_DeductBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).DeductBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_DeductBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).DeductBudget(ctx, req.(*DeductBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_GetBudgetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).GetBudgetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_GetBudgetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).GetBudgetInfo(ctx, req.(*GetBudgetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_RefundBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).RefundBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_RefundBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).RefundBudget(ctx, req.(*RefundBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BudgetService_ServiceDesc is the grpc.ServiceDesc for BudgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BudgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "budget.BudgetService",
	HandlerType: (*BudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBudget",
			Handler:    _BudgetService_CheckBudget_Handler,
		},
		{
			MethodName: "DeductBudget",
			Handler:    _BudgetService_DeductBudget_Handler,
		},
		{
			MethodName: "GetBudgetInfo",
			Handler:    _BudgetService_GetBudgetInfo_Handler,
		},
		{
			MethodName: "RefundBudget",
			Handler:    _BudgetService_RefundBudget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/budget.proto",
}
